project:
  type: website

website:
  title: "team7-project"
  navbar:
    left:
      - href: index.qmd
        text: Introduction & Research Rationale
      - about.qmd
      - eda.qmd
      - career_plan.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



